backend:
  name: test-repo # git-gateway for proxy server
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/img
public_folder: img
publish_mode: editorial_workflow
collections: # A list of collections the CMS should be able to edit  - 
- name: "strategies"
  label: "Strategies" 
  folder: _strategies
  create: true
  fields: # The fields each document in this collection have
    - { label: "Name", name: "name",widget: "string"}
    - { label: "Version", name: "version", widget: "string"}
    - { label: "Title", name: "title", widget: "string"}
    - { label: "Description", name: "description", widget: "markdown" }
    - { label: "useContext", name: "useContext", widget: "string"}
    - label: 'Type' 
      name: "type" 
      widget: "list" 
      fields: 
        - { label: "Order Set", name: "order-set", widget: "string"}
        - { label: "Clinical Protocol", name: "clinical-protocol", widget: "string"}
        - { label: "ECA Rule", name: "eca-rule", widget: "string"}
        - { label: "Workflow Definition", name: "workflow-definition", widget: "string"}
    - label: 'Status'
      name: "status" 
      widget: "list" 
      fields:
        - { label: "Draft", name: "draft", widget: "string"}
        - { label: "Active", name: "active", widget: "string"}
        - { label: "Retired", name: "retired", widget: "string"}
        - { label: "Unknown", name: "unknown", widget: "string"}
    - { label: "Publisher", name: "publisher", widget: "string"}

      # - label: 'Endorsement'
      #   name: "endorsement"
      #   widget: "select"
      #   options: ["endorsed", "not endorsed"]
      #   default: ["endorsed"]
      # - label: 'Authors'
      #   name: "authors"
      #   widget: list
      #   field: { label: "Author", name: "author", widget: "string"}
      # - { label: "Publish Date", name: "date", widget: "datetime", format: YYYY.MM.DD }
      # - label: 'Citations'
      #   name: "citations"
      #   widget: list
      #   field: { label: "Citation", name: "Citation", widget: "string"}